### ISSUE TITLE
变分推断部分请教

### ISSUE THREAD

**Issue by starry-sky6688** [TonghanWang/EITI-EDTI#1]
请问变分推断的具体代码在哪一部分呢？

**Comment by starry-sky6688** [comment]
找到啦，不好意思打扰了~

**Comment by TonghanWang** [comment]
:) Please feel free to contact us if you have any other questions

**Comment by starry-sky6688** [comment]
您好，请问变分推断中的ELBO是在哪里定义的呢？pycharm无法定位VI类中的self.model.losses。

另外想问它的loss中的 negative log-likelihood的作用是什么呢？

期待您的回复，十分感谢~
![image](https://user-images.githubusercontent.com/38175678/90462781-fbad9a80-e13b-11ea-85ea-c669ef7ca331.png)

**Comment by wjh720** [comment]
> 您好，请问变分推断中的ELBO是在哪里定义的呢？pycharm无法定位VI类中的self.model.losses。
> 
> 另外想问它的loss中的 negative log-likelihood的作用是什么呢？
> 
> 期待您的回复，十分感谢~
> ![image](https://user-images.githubusercontent.com/38175678/90462781-fbad9a80-e13b-11ea-85ea-c669ef7ca331.png)

Please refer to tfp.layers.DenseReparameterization for details.

**Comment by starry-sky6688** [comment]
嗯嗯好的，十分感谢，原来我的电脑上没装tfp。
